### ISSUE TITLE
submodule repository missing

### ISSUE THREAD

**Issue by eyeco** [textiles-lab/knitout-frontend-js#12]
I am unable to access the submodule repo (apparently this should be [https://github.com/textiles-lab/knitout-api.git](https://github.com/textiles-lab/knitout-api)?) Also on the Github web frontend, this link gives me a 404. Is this referencing an internal project of yours?

**Comment by ixchow** [comment]
Yeah, and it's not clear why -- I think it was added by mistake and nobody has noticed because the submodule isn't fetched if you `npm install knitout`.

**Comment by ixchow** [comment]
(Patched out in a1e20de75d980092b0f3e93207eecc5401b17747 )

**Comment by eyeco** [comment]
Wasn't aware of the npm package, thanks.
